name: Challenge 1 - Basic

env:
  # This forces the runner to use Node 24 for your actions
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
jobs:
  basics:
    runs-on: ubuntu-latest
    steps:
      - name: Print basics
        run: |
          echo "Workflow started"
          echo "ref=$GITHUB_REF"
          echo "runner=$RUNNER_OS"
