name: Challenge 1 - Basic

on:
  workflow_dispatch:
jobs:
  basics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print basics
        run: |
          echo "Workflow started"
          echo "ref=$GITHUB_REF"
          echo "runner=$RUNNER_OS"
