name: Exercise 2 - Variable Management

on:
  workflow_dispatch:
  push:

jobs:
  variable-practice:
    runs-on: ubuntu-latest
    steps: # Line 9: This must be indented exactly 4 spaces
      - name: "Step1: Set the variable"
        shell: pwsh
        run: |
          # 1. Clean the server string
          $server = "myserver.database.windows.net,1443" -replace '[,:]\d+$',''
          
          # 2. Save the variable to the github environment
          # Use $env: to tell PowerShell to look at the System Environment Variables
          Add-Content -Path $env:GITHUB_ENV -Value "clean_server=$server"
          Write-Output "Server name saved to environment"
         
      - name: "step2 read the variable"
        shell: pwsh
        run: |
          Write-Output "The value is : $env:clean_server"
